package configgen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tensorov/reverse-ssh-gateway/internal/registry"
)

// setupTestDir creates a temporary directory for testing.
func setupTestDir(t *testing.T) string {
	t.Helper()
	return t.TempDir()
}

// readConfig reads the generated config file and returns its content.
func readConfig(t *testing.T, configDir string) string {
	t.Helper()
	configPath := filepath.Join(configDir, "rtg-services.yml")
	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("read config: %v", err)
	}
	return string(data)
}

// ─── Happy: HTTP with domain → config contains HTTP router + TLS ─────────────

func TestGenerateHttpWithDomain(t *testing.T) {
	dir := setupTestDir(t)

	services := []registry.Service{
		{Host: "vps-b", Port: 8080, Domain: "myapp.zeitoven.ru", Proto: "http", TTL: 30},
	}

	err := Generate(services, dir)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	content := readConfig(t, dir)

	if !strings.Contains(content, "myapp-zeitoven-ru") {
		t.Error("expected router name 'myapp-zeitoven-ru' in config")
	}
	if !strings.Contains(content, "Host(`myapp.zeitoven.ru`)") {
		t.Error("expected Host rule with domain")
	}
	if !strings.Contains(content, "certResolver: default") {
		t.Error("expected TLS certResolver")
	}
	if !strings.Contains(content, "url: \"http://vps-b:8080\"") {
		t.Error("expected service URL")
	}
}

// ─── Happy: TCP without domain → config contains TCP router ──────────────────

func TestGenerateTcpWithoutDomain(t *testing.T) {
	dir := setupTestDir(t)

	services := []registry.Service{
		{Host: "vps-c", Port: 5432, Proto: "tcp", TTL: 30},
	}

	err := Generate(services, dir)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	content := readConfig(t, dir)

	if !strings.Contains(content, "tcp:") {
		t.Error("expected tcp section in config")
	}
	if !strings.Contains(content, "vps-c-5432") {
		t.Error("expected router name 'vps-c-5432' in config")
	}
	if !strings.Contains(content, "tunnel-5432") {
		t.Error("expected entryPoint 'tunnel-5432'")
	}
	if !strings.Contains(content, "HostSNI(`*`)") {
		t.Error("expected HostSNI rule")
	}
	if !strings.Contains(content, "address: \"vps-c:5432\"") {
		t.Error("expected service address")
	}
}

// ─── Happy: Multiple services (HTTP + TCP) in one config ─────────────────────

func TestGenerateMixedServices(t *testing.T) {
	dir := setupTestDir(t)

	services := []registry.Service{
		{Host: "vps-b", Port: 8080, Domain: "app1.zeitoven.ru", Proto: "http", TTL: 30},
		{Host: "vps-c", Port: 5432, Proto: "tcp", TTL: 30},
		{Host: "vps-d", Port: 3306, Proto: "tcp", TTL: 30},
	}

	err := Generate(services, dir)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	content := readConfig(t, dir)

	// Should contain both http and tcp sections
	if !strings.Contains(content, "http:") {
		t.Error("expected http section")
	}
	if !strings.Contains(content, "tcp:") {
		t.Error("expected tcp section")
	}

	// Should contain all three services
	if !strings.Contains(content, "app1-zeitoven-ru") {
		t.Error("expected HTTP router app1-zeitoven-ru")
	}
	if !strings.Contains(content, "vps-c-5432") {
		t.Error("expected TCP router vps-c-5432")
	}
	if !strings.Contains(content, "vps-d-3306") {
		t.Error("expected TCP router vps-d-3306")
	}
}

// ─── Happy: Empty services generates header-only config ──────────────────────

func TestGenerateEmptyServices(t *testing.T) {
	dir := setupTestDir(t)

	err := Generate(nil, dir)
	if err != nil {
		t.Fatalf("Generate with nil: %v", err)
	}

	content := readConfig(t, dir)
	if !strings.Contains(content, "Auto-generated by rtg-orchestrator") {
		t.Error("expected header comment")
	}
}

// ─── Happy: Delete → router removed (only remaining services) ────────────────

func TestGenerateAfterDelete(t *testing.T) {
	dir := setupTestDir(t)

	// Generate with two services
	services := []registry.Service{
		{Host: "vps-b", Port: 8080, Domain: "app1.zeitoven.ru", Proto: "http", TTL: 30},
		{Host: "vps-c", Port: 5432, Proto: "tcp", TTL: 30},
	}
	if err := Generate(services, dir); err != nil {
		t.Fatalf("Generate initial: %v", err)
	}

	// Generate with only one remaining (simulates delete)
	remaining := []registry.Service{
		{Host: "vps-c", Port: 5432, Proto: "tcp", TTL: 30},
	}
	if err := Generate(remaining, dir); err != nil {
		t.Fatalf("Generate after delete: %v", err)
	}

	content := readConfig(t, dir)

	// vps-c should still be there
	if !strings.Contains(content, "vps-c-5432") {
		t.Error("expected remaining TCP router vps-c-5432")
	}

	// app1 should be gone
	if strings.Contains(content, "app1-zeitoven-ru") {
		t.Error("removed service should not appear in config")
	}
}

// ─── Failure: HTTP without domain is silently skipped ────────────────────────

func TestGenerateHttpWithoutDomain(t *testing.T) {
	dir := setupTestDir(t)

	// HTTP service without domain — should be skipped
	services := []registry.Service{
		{Host: "vps-b", Port: 8080, Proto: "http", TTL: 30},
	}

	err := Generate(services, dir)
	if err != nil {
		t.Fatalf("Generate with HTTP without domain: %v", err)
	}

	content := readConfig(t, dir)

	// Should NOT contain any HTTP router entries
	if strings.Contains(content, "vps-b-8080") {
		t.Error("HTTP service without domain should not have a router")
	}

	// Should still have header (but no http or tcp sections)
	if strings.Contains(content, "http:") {
		t.Error("should not contain http section with no valid HTTP routers")
	}
}

// ─── Failure: Invalid proto is silently skipped ──────────────────────────────

func TestGenerateInvalidProto(t *testing.T) {
	dir := setupTestDir(t)

	services := []registry.Service{
		{Host: "vps-b", Port: 8080, Proto: "udp", TTL: 30},
	}

	err := Generate(services, dir)
	if err != nil {
		t.Fatalf("Generate with invalid proto: %v", err)
	}

	content := readConfig(t, dir)
	if !strings.Contains(content, "Auto-generated by rtg-orchestrator") {
		t.Error("expected header comment even with skipped services")
	}
}

// ─── Adversarial: Simulate crash mid-write → config file not corrupted ───────

func TestAtomicWritePowerLoss(t *testing.T) {
	dir := setupTestDir(t)

	// First, write a valid config
	initialServices := []registry.Service{
		{Host: "vps-b", Port: 8080, Domain: "app.zeitoven.ru", Proto: "http", TTL: 30},
	}
	if err := Generate(initialServices, dir); err != nil {
		t.Fatalf("Generate initial: %v", err)
	}

	originalContent := readConfig(t, dir)

	// Simulate power loss: write a .tmp file but don't rename it
	tmpPath := filepath.Join(dir, "rtg-services.yml.tmp")
	corruptContent := "corrupted data that should not end up in the real file"
	if err := os.WriteFile(tmpPath, []byte(corruptContent), 0o644); err != nil {
		t.Fatalf("write tmp: %v", err)
	}

	// Verify the real config file is intact
	currentContent := readConfig(t, dir)
	if currentContent != originalContent {
		t.Error("config file was corrupted by interrupted write")
	}
	if strings.Contains(currentContent, "corrupted") {
		t.Error("config contains corrupted data from tmp file")
	}

	// Clean up: on next successful Generate, tmp is removed and config is updated
	newServices := []registry.Service{
		{Host: "vps-c", Port: 5432, Proto: "tcp", TTL: 30},
	}
	if err := Generate(newServices, dir); err != nil {
		t.Fatalf("Generate after simulated crash: %v", err)
	}

	// Verify old tmp is cleaned up
	if _, err := os.Stat(tmpPath); !os.IsNotExist(err) {
		t.Error(".tmp file should not exist after successful Generate")
	}

	// Verify new config has the TCP service
	content := readConfig(t, dir)
	if !strings.Contains(content, "vps-c-5432") {
		t.Error("expected TCP service after crash recovery")
	}
}

// ─── Adversarial: Parallel Generate calls don't corrupt config ───────────────

func TestGenerateIdempotent(t *testing.T) {
	dir := setupTestDir(t)

	services := []registry.Service{
		{Host: "vps-b", Port: 8080, Domain: "app.zeitoven.ru", Proto: "http", TTL: 30},
	}

	// Generate multiple times — should produce identical output
	if err := Generate(services, dir); err != nil {
		t.Fatalf("Generate #1: %v", err)
	}
	content1 := readConfig(t, dir)

	if err := Generate(services, dir); err != nil {
		t.Fatalf("Generate #2: %v", err)
	}
	content2 := readConfig(t, dir)

	if content1 != content2 {
		t.Error("idempotent Generate calls should produce identical output")
	}
}

// ─── Verify generated YAML is parseable (basic structure) ───────────────────

func TestGeneratedYamlStructure(t *testing.T) {
	dir := setupTestDir(t)

	services := []registry.Service{
		{Host: "vps-b", Port: 8080, Domain: "myapp.zeitoven.ru", Proto: "http", TTL: 30},
		{Host: "vps-c", Port: 5432, Proto: "tcp", TTL: 30},
	}

	if err := Generate(services, dir); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	content := readConfig(t, dir)

	// Check overall structure
	lines := strings.Split(content, "\n")

	// First line should be header
	if !strings.HasPrefix(lines[0], "# Auto-generated") {
		t.Error("first line should be header comment")
	}

	// Check indentation consistency
	for _, line := range lines {
		trimmed := strings.TrimLeft(line, " ")
		indent := len(line) - len(trimmed)
		if indent%2 != 0 {
			t.Errorf("odd indentation at line: %q (indent=%d)", line, indent)
		}
	}
}
