// Package configgen generates Traefik dynamic configuration from the service registry.
//
// All output is generated as YAML in Traefik file provider format using only
// stdlib (strings.Builder). The config file is written atomically: write to .tmp,
// rename over old file, old .tmp is removed.
package configgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tensorov/reverse-ssh-gateway/internal/registry"
)

// configFileName is the name of the generated Traefik config file.
const configFileName = "rtg-services.yml"

// Generate creates or updates the Traefik dynamic config file at
// configDir/rtg-services.yml from the given services. Atomic write is
// guaranteed via write-to-tmp-then-rename.
//
// Services with proto="http" require a non-empty Domain to generate an HTTP
// router; they are silently skipped when Domain is empty. Services with
// proto="tcp" always generate a TCP router. Unknown proto values are skipped.
func Generate(services []registry.Service, configDir string) error {
	content := buildYAML(services)

	// Ensure config directory exists.
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	return atomicWrite(configDir, configFileName, content)
}

// safeName converts a domain name to a Traefik-safe router name by replacing
// dots and colons with dashes. Example: "myapp.zeitoven.ru" → "myapp-zeitoven-ru".
func safeName(domain string) string {
	name := strings.ReplaceAll(domain, ".", "-")
	name = strings.ReplaceAll(name, ":", "-")
	return name
}

// buildYAML generates the complete YAML content from the given services.
// Returns just a header comment when no valid services are provided.
func buildYAML(services []registry.Service) string {
	var httpRouters, httpServices strings.Builder
	var tcpRouters, tcpServices strings.Builder

	for _, svc := range services {
		switch svc.Proto {
		case "http":
			if svc.Domain == "" {
				// HTTP requires a domain — skip silently.
				continue
			}
			writeHTTPRouter(&httpRouters, svc)
			writeHTTPService(&httpServices, svc)
		case "tcp":
			writeTCPRouter(&tcpRouters, svc)
			writeTCPService(&tcpServices, svc)
		}
	}

	var buf strings.Builder
	buf.WriteString("# Auto-generated by rtg-orchestrator — DO NOT EDIT\n")

	if httpRouters.Len() > 0 {
		buf.WriteString("http:\n  routers:\n")
		buf.WriteString(httpRouters.String())
		buf.WriteString("  services:\n")
		buf.WriteString(httpServices.String())
	}

	if tcpRouters.Len() > 0 {
		buf.WriteString("tcp:\n  routers:\n")
		buf.WriteString(tcpRouters.String())
		buf.WriteString("  services:\n")
		buf.WriteString(tcpServices.String())
	}

	return buf.String()
}

// writeHTTPRouter appends a Traefik HTTP router YAML block for the given service.
func writeHTTPRouter(buf *strings.Builder, svc registry.Service) {
	routerName := safeName(svc.Domain)
	svcName := routerName + "-svc"

	fmt.Fprintf(buf, "    %s:\n", routerName)
	fmt.Fprintf(buf, "      rule: \"Host(`%s`)\"\n", svc.Domain)
	fmt.Fprintf(buf, "      entryPoints: [\"web-secure\"]\n")
	fmt.Fprintf(buf, "      tls:\n")
	fmt.Fprintf(buf, "        certResolver: default\n")
	fmt.Fprintf(buf, "      service: %s\n", svcName)
}

// writeHTTPService appends a Traefik HTTP service YAML block for the given service.
func writeHTTPService(buf *strings.Builder, svc registry.Service) {
	routerName := safeName(svc.Domain)
	svcName := routerName + "-svc"

	fmt.Fprintf(buf, "    %s:\n", svcName)
	fmt.Fprintf(buf, "      loadBalancer:\n")
	fmt.Fprintf(buf, "        servers:\n")
	fmt.Fprintf(buf, "          - url: \"http://%s:%d\"\n", svc.Host, svc.Port)
}

// writeTCPRouter appends a Traefik TCP router YAML block for the given service.
func writeTCPRouter(buf *strings.Builder, svc registry.Service) {
	routerName := fmt.Sprintf("%s-%d", svc.Host, svc.Port)
	svcName := routerName + "-svc"

	fmt.Fprintf(buf, "    %s:\n", routerName)
	fmt.Fprintf(buf, "      entryPoints: [\"tunnel-%d\"]\n", svc.Port)
	fmt.Fprintf(buf, "      rule: \"HostSNI(`*`)\"\n")
	fmt.Fprintf(buf, "      service: %s\n", svcName)
}

// writeTCPService appends a Traefik TCP service YAML block for the given service.
func writeTCPService(buf *strings.Builder, svc registry.Service) {
	routerName := fmt.Sprintf("%s-%d", svc.Host, svc.Port)
	svcName := routerName + "-svc"

	fmt.Fprintf(buf, "    %s:\n", svcName)
	fmt.Fprintf(buf, "      loadBalancer:\n")
	fmt.Fprintf(buf, "        servers:\n")
	fmt.Fprintf(buf, "          - address: \"%s:%d\"\n", svc.Host, svc.Port)
}

// atomicWrite writes content to a .tmp file, then renames it over the target
// file, then removes the old .tmp if it still exists. This provides atomic
// updates on POSIX systems where rename(2) is atomic on the same filesystem.
func atomicWrite(configDir, fileName, content string) error {
	filePath := filepath.Join(configDir, fileName)
	tmpPath := filepath.Join(configDir, fileName+".tmp")

	// Remove any stale .tmp file from a previous crash.
	if err := os.Remove(tmpPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove stale tmp: %w", err)
	}

	// Write to .tmp.
	if err := os.WriteFile(tmpPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write tmp file: %w", err)
	}

	// Atomic rename: replaces the old file atomically on POSIX.
	if err := os.Rename(tmpPath, filePath); err != nil {
		// Clean up .tmp on rename failure.
		os.Remove(tmpPath)
		return fmt.Errorf("rename tmp to config: %w", err)
	}

	return nil
}
